---
title: "Schools analysis - Prim and Sec - 28/11/23"
output: 
  html_document:
    css: Wil_style.css
    theme: default
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
always_allow_html: yes
---

```{r setup1, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(zoo)
library(data.table)
library(tidyverse)
library(gglaplot)
library(ggplot2)
library(scales)
library(readxl)
library(knitr)
library(sf)
library(sp)
library(kableExtra)
library(magick)

library(plotly)    
library(RColorBrewer)
library(htmltools)
library(prettydoc)
library(rmdformats)
library(ggrepel)

chart_dir <- 'CHARTS/'

data_dir <- 'DATA/'

# Disable scientific notation
options(scipen=999)

```


```{r setup2, include=FALSE}

#boroughcodes <- read.csv("C:/Migration/Migration_R/DATA/Domestic/InnerLondon.csv") %>%   
#  data.frame

boroughcodes <- fread(paste0(data_dir,"InnerLondon.csv")) %>%   
  data.frame


## SCHOOLS DATA For children 

# Input data for headcounts of primary school children since 2015 and merge with Inner/Outer file.

# These are data from the DFE website.

input_London_primary_schools <- fread(paste0(data_dir,"London_State_primary_pupils_201516_to_202223.csv")) %>%
  left_join(boroughcodes, by=c("new_la_code"="BoroughCode"))%>% 
  mutate(across(c(Inner, la_name), factor)) %>%
  mutate(Inner_factor= recode(Inner, "1"="Inner", "0"="Outer")) %>%
   data.frame() 

```


```{r fig_London_prim_schools_line_1, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Plot primary schools numbers over time by borough, not adjusted for population

catcolour2 = rev(c('#d82222', '#6da7de'))

London_schools_lines <- input_London_primary_schools %>%
  filter(BoroughName != "City of London") %>%
  ggplot(aes(x = period2, y = headcount, group = BoroughName, color = Inner_factor
             , text = paste("Year  :", period2,
                            "<br>Borough : ", BoroughName,
                            "<br>Head count ", round(headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line() + 
 scale_color_manual(name='Zone:', values = catcolour2) +
  labs(title= "Primary schools headcount, London, 2015 - 2022", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggplotly(London_schools_lines, tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white")) %>%
  layout(title= list(x = 0.05,
                     text = "<b>Primary schools headcount, London, 2015 - 2022<b>", 
                     font=list(size = 15, family = "Arial")))



```


```{r fig_London_prim_schools_line_2, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Plot London primary schools numbers over time, by borough, indexed to 201516 value

London_schools_lines_ind <- input_London_primary_schools %>%
  filter(BoroughName != "City of London") %>%
  group_by(BoroughName) %>% 
  mutate(indexed_headcount = (headcount/first(headcount))*100) %>% 
  ggplot(aes(x = period2, y = indexed_headcount, group = BoroughName, color = Inner_factor
             , text = paste("Year  :", period2,
                            "<br>Borough : ", BoroughName,
                            "<br>Head count as % of 2015 ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line() + 
  geom_hline(yintercept=100)+
 scale_color_manual(name='Zone:', values = catcolour2) +
  labs(title= "Primary schools headcount, London, 2015 - 2022, indexed to 2015", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggplotly(London_schools_lines_ind, tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white")) %>%
  layout(title= list(x = 0.05,
                     text = "<b>Primary schools headcount, indexed to 2015<b>", 
                     font=list(size = 15, family = "Arial")))

```


```{r fig_London_Prim_schools_line_3, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Aggregate by zone of London, and plot again

agg_input_london_primary_schools <- input_London_primary_schools %>%
  filter(BoroughName != "City of London") %>%
  group_by(period2, Inner_factor) %>% 
  summarise(agg_headcount = sum(headcount)) %>%
  data.frame()

London_schools_agg_lines <- agg_input_london_primary_schools %>%
   ggplot(aes(x = period2, y = agg_headcount/1000, group = Inner_factor, color = Inner_factor
             , text = paste("Year  :", period2,
                            "<br>Zone : ", Inner_factor,
                            "<br>Headcount : ", round(agg_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line() + 
 scale_color_manual(name='Zone:', values = catcolour2) +
  labs(title= "Primary schools headcount by Zone, London, 2015 - 2022", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggplotly(London_schools_agg_lines, tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white")) %>%
  layout(title= list(x = 0.05,
                     text = "<b>Primary schools headcount by Zone, London, 2015 - 2022, London<b>", 
                     font=list(size = 15, family = "Arial")))



```


```{r fig_London_Prim_schools_line_4, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Index aggregated values to 201516 value

London_schools_agg_ind_lines <- agg_input_london_primary_schools %>%
   group_by(Inner_factor) %>% 
   mutate(indexed_headcount = (agg_headcount/first(agg_headcount))*100) %>% 
   ggplot(aes(x = period2, y = indexed_headcount, group = Inner_factor, color = Inner_factor
             , text = paste("Year  :", period2,
                            "<br>Zone : ", Inner_factor,
                            "<br>Head count as % of 2015 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line() + 
  geom_hline(yintercept=100)+
  scale_y_continuous(breaks = seq(88, 102, 2)) + #, limits = c(88, 102)) +
 scale_color_manual(name='Zone:', values = catcolour2) +
  labs(title= "Primary schools headcount by Zone, London, 2015 - 2022, indexed to 2015", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggplotly(London_schools_agg_ind_lines, tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white")) %>%
  layout(title= list(x = 0.05,
                     text = "<b>Primary schools headcount by Zone, indexed to 2015, London<b>", 
                     font=list(size = 15, family = "Arial")))


```


```{r setup3, include=FALSE}

# SCHOOLS DATA For children in London, going further back in time.

# These are data that Ben provided.

boroughcodes <- fread(paste0(data_dir,"InnerLondon.csv")) %>%   
  data.frame

cityORcounty_codes <- fread(paste0(data_dir,"cityORcounty.csv")) %>%   
  data.frame

# Input data for headcounts of children and merge with city/county file

input_all_schools_data <- fread(paste0(data_dir,"pupils_lad_type_age_2009to22.csv")) %>%
  full_join(cityORcounty_codes, by=c("new_la_code"= "la_code"), keep = TRUE)%>% 
  mutate(across(c(cityORcounty_code, cityORcounty_name), factor)) %>%
 data.frame() 


```



```{r fig_London_Prim_schools_line_5, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

catcolour2 = rev(c('#d82222', '#6da7de'))

# Aggregate by Zone of London

agg_input_london_primary_schools <- input_all_schools_data %>%
  filter(grepl('E09', new_la_code)) %>%
  filter(la_name.x != "City of London") %>%
  filter(age < 11) %>%
  filter(type == "State-funded") %>%
  group_by(period_start, cityORcounty_name) %>% 
  summarise(agg_full_time = sum(full_time)) %>%
 # mutate(Year = as.character(year)) %>%
  data.frame()

London_schools_agg_lines <- agg_input_london_primary_schools %>%
   ggplot(aes(x = period_start, y = agg_full_time/1000, group = cityORcounty_name, color = cityORcounty_name, 
             text = paste("Year  :", period_start,
                            "<br>Zone : ", cityORcounty_name,
                            "<br>Headcount : ", round(agg_full_time, digits = 0))
  )) +
  theme_gla() +
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right") +
  geom_line(size = 1) + 
  scale_color_manual(name='Zone:', values = rev(catcolour2)) +
  labs(title= "State-funded full-time primary school pupils by Zone, London, 2009 - 2022", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
London_schools_agg_lines

# ggplotly(London_schools_agg_lines, tooltip = "text") %>%
#   style(hoverlabel = list(bgcolor = "white")) %>%
#   layout(title= list(x = 0.05,
#                      text = "<b>State-funded full-time primary school pupils, London, 2009 - 2022<b>", 
#                      font=list(size = 15, family = "Arial")),        yaxis = list(title = list(text ='Full-time students (thousands)', 
#                                    font = list(size = 15, family = "Arial", color = "black", 
#                                                fontface = "bold")))) 


```

```{r fig_London_Prim_schools_line_6, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

# Index aggregated values to 2009 value

London_schools_agg_ind2009_lines <- agg_input_london_primary_schools %>%
   group_by(cityORcounty_name) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 
   ggplot(aes(x = period_start, y = indexed_headcount, group = cityORcounty_name, color = cityORcounty_name
             , text = paste("Year  :", period_start,
                            "<br>Zone : ", cityORcounty_name,
                            "<br>Head count as % of 2009 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line(size = 1) + 
  geom_hline(yintercept=100)+
   theme(plot.title = element_text(size = 16)) +
  theme(legend.position = "right") +
 # scale_y_continuous(breaks = seq(88, 102, 2)) + #, limits = c(88, 102)) +
 scale_color_manual(name='Zone:', values = rev(catcolour2)) +
  labs(title= "State-funded full-time primary school pupils by Zone, London, 2009 - 2022", 
       subtitle = "Indexed to 2009", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
London_schools_agg_ind2009_lines

# ggsave (filename = (paste0(chart_dir, "London_schools_agg_ind2009_lines.png")),
#          plot = London_schools_agg_ind2009_lines,
#          device = "png",
#          dpi=600,
#          width = 9,
#          units = "in")
# 
# 
# ggplotly(London_schools_agg_ind2009_lines, tooltip = "text") %>%
#   style(hoverlabel = list(bgcolor = "white")) %>%
#   layout(title= list(x = 0.05,
#                      text = "<b>State-funded full-time primary school pupils by Zone, London, 2009 - 2022, indexed to 2009<b>", 
#                      font=list(size = 15, family = "Arial")))
# 


```



```{r fig_London_Prim_schools_line_7, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

catcolour2 = rev(c('#d82222', '#6da7de'))

# Plot by individual borough

agg_input_london_primary_schools_borough <- input_all_schools_data %>%
  filter(grepl('E09', new_la_code)) %>%
  filter(la_name.x != "City of London") %>%
  filter(age < 11) %>%
  filter(type == "State-funded") %>%
  group_by(period_start, la_name.x, cityORcounty_name) %>% 
  summarise(agg_full_time = sum(full_time)) %>%
# mutate(Year = as.character(year)) %>%
  data.frame()

London_schools_agg_borough_lines <- agg_input_london_primary_schools_borough %>%
   ggplot(aes(x = period_start, y = agg_full_time/1000, group = la_name.x, color = cityORcounty_name,
             text = paste("Year  :", period_start,
                            "<br>Zone : ", la_name.x,
                            "<br>Headcount : ", round(agg_full_time, digits = 0))
  )) +
  theme_gla() +
  geom_line() + 
  scale_color_manual(name='Zone:', values = rev(catcolour2)) +
  labs(title= "State-funded full-time primary school pupils, London, 2009 - 2022", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggplotly(London_schools_agg_borough_lines, tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white")) %>%
  layout(title= list(x = 0.05,
                     text = "<b>State-funded full-time primary school pupils, 2009 - 2022, London boroughs<b>", 
                     font=list(size = 15, family = "Arial")),        yaxis = list(title = list(text ='Full-time students (thousands)', 
                                   font = list(size = 15, family = "Arial", color = "black", 
                                               fontface = "bold")))) 


```


```{r fig_London_Prim_schools_line_8, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Index aggregated values to 2009 value

London_schools_agg_ind2009_borough_lines <- agg_input_london_primary_schools_borough %>%
   group_by(la_name.x) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 
   ggplot(aes(x = period_start, y = indexed_headcount, group = la_name.x, color = cityORcounty_name
             , text = paste("Year  :", period_start,
                            "<br>Zone : ", la_name.x,
                            "<br>Head count as % of 2009 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line() + 
  geom_hline(yintercept=100)+
 # scale_y_continuous(breaks = seq(88, 102, 2)) + #, limits = c(88, 102)) +
 scale_color_manual(name='Zone:', values = rev(catcolour2)) +
  labs(title= "Primary schools headcount, London, 2009- 2022, indexed to 2009 value", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

# ggsave (filename = (paste0(chart_dir, "London_schools_agg_ind2009_borough_lines.png")),
#          plot = London_schools_agg_ind2009_borough_lines,
#          device = "png",
#          dpi=600,
#          width = 9,
#          units = "in")


ggplotly(London_schools_agg_ind2009_borough_lines, tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white")) %>%
  layout(title= list(x = 0.05,
                     text = "<b>Primary schools headcount, indexed to 2009, London boroughs <b>", 
                     font=list(size = 15, family = "Arial")))


```


```{r fig_Rest_ofEng_Prim_schools_line_1, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

my_pal = gla_pal(palette_type = "categorical",
        palette_name = "core", n = 9)

# Now plot schools data by English region

# Aggregate by region 

region_primary_schools <- input_all_schools_data %>%
  filter(la_name.x != "City of London") %>%
  filter(age < 11) %>%
  filter(type == "State-funded") %>%
  group_by(period_start, region_name) %>% 
  summarise(agg_full_time = sum(full_time)) %>%
 # mutate(Year = as.character(year)) %>%
  data.frame()

regions_primary_schools_lines <- region_primary_schools %>%
   ggplot(aes(x = period_start, y = agg_full_time, group = region_name, color = region_name,
             text = paste("Year  :", period_start,
                            "<br>Zone : ", region_name,
                            "<br>Headcount : ", round(agg_full_time, digits = 0))
  )) +
  theme_gla() +
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right") +
  geom_line(size = 1) + 
    scale_y_continuous(labels = label_number(suffix = "K", scale = 1e-3, big.mark = ","))+
  scale_color_manual(name='Zone:', values = my_pal) +
  labs(title= "State-funded full-time primary school pupils, by region of England, 2009 - 2022", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
regions_primary_schools_lines

```


```{r fig_Rest_ofEng_Prim_schools_line_2, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

# Index aggregated values to 2009 value

region_ind2009_lines <- region_primary_schools %>%
   group_by(region_name) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 
   ggplot(aes(x = period_start, y = indexed_headcount, group = region_name, color = region_name
             , text = paste("Year  :", period_start,
                            "<br>Zone : ", region_name,
                            "<br>Head count as % of 2009 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line(size = 1) + 
  geom_hline(yintercept=100)+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right") +
 # scale_y_continuous(breaks = seq(88, 102, 2)) + #, limits = c(88, 102)) +
 scale_color_manual(name='Zone:', values = my_pal) +
  labs(title= "State-funded full-time primary school pupils, by regions of England, 2009 - 2022, indexed to 2009", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
#region_ind2009_lines

ggsave (filename = (paste0(chart_dir, "region_ind2009_lines.png")),
         plot = region_ind2009_lines,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")


ggplotly(region_ind2009_lines, tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white")) %>%
  layout(title= list(x = 0.05,
                     text = "<b>State-funded full-time primary school pupils, by regions of England, 2009 - 2022, indexed to 2009<b>", 
                     font=list(size = 15, family = "Arial")))


```



```{r fig_Rest_ofEng_Prim_schools_line_3, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

# Aggregate to two categories, London and the rest of England, and index to 2009 value

catcolour2 = rev(c('#d82222', '#6da7de'))

London_orNot <- region_primary_schools %>%
  mutate(london = case_when(region_name == "London" ~ "London",  TRUE ~ "Rest of England")) %>%
  mutate(london_factor = as.factor(london)) %>%
   group_by(period_start, london_factor) %>% 
  summarise(agg_agg_full_time = sum(agg_full_time)) %>%
  data.frame()
  

London_orNot_ind2009_lines <- London_orNot %>%
   group_by(london_factor) %>% 
   mutate(indexed_headcount = (agg_agg_full_time/first(agg_agg_full_time))*100) %>% 
   ggplot(aes(x = period_start, y = indexed_headcount, group = london_factor, color = london_factor
             , text = paste("Year  :", period_start,
                            "<br>Zone : ", london_factor,
                            "<br>Head count as % of 2009 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line(size = 1) + 
  geom_hline(yintercept=100)+
   theme(plot.title = element_text(size = 16)) + #  ,hjust = 0.5
  theme(legend.position = "right") +
 scale_colour_manual(values=c("#943fa6", "#5ea15d"), 
                       name="Zone") +
labs(title= "Change in state-funded full-time primary school pupils, 2009 - 2022",
            subtitle = "Indexed to 2009", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
London_orNot_ind2009_lines


```


```{r fig_Rest_ofEng_Prim_schools_line_4, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

# Add rest of England indexed plot to London zone indexed plot

Inner_London_schools_agg_ind2009 <- agg_input_london_primary_schools %>%
    filter(cityORcounty_name == "Inner London") %>%
    group_by(cityORcounty_name) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 

       mutate(label = if_else(period_start == max(period_start), 
                         as.character(cityORcounty_name), NA_character_)) %>%
  data.frame()

Outer_London_schools_agg_ind2009 <- agg_input_london_primary_schools %>%
     filter(cityORcounty_name == "Outer London") %>%
   group_by(cityORcounty_name) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 

      mutate(label = if_else(period_start == max(period_start), 
                         as.character(cityORcounty_name), NA_character_)) %>%
  data.frame()

RestofEng_ind2009 <- London_orNot %>%
  filter(london_factor == "Rest of England") %>%   
  group_by(london_factor) %>% 
   mutate(indexed_headcount = (agg_agg_full_time/first(agg_agg_full_time))*100) %>% 

      mutate(label = if_else(period_start == max(period_start), 
                         as.character(london_factor), NA_character_)) %>%
  data.frame()

LondonZone_orNot_ind2009_lines <-
   ggplot() +
  theme_gla() +
  geom_line(data = Inner_London_schools_agg_ind2009, aes(x = period_start, 
                                                         y = indexed_headcount, group = 1), 
            color = '#d82222', size = 1) +
    geom_label_repel(data = Inner_London_schools_agg_ind2009,aes(x = period_start, y = indexed_headcount,label = label), nudge_x = 1, color = '#d82222')+
    geom_line(data = Outer_London_schools_agg_ind2009, aes(x = period_start, 
                                                           y = indexed_headcount, group = 1), 
              color = '#6da7de', size = 1) +
    geom_label_repel(data = Outer_London_schools_agg_ind2009, aes(x = period_start, y = indexed_headcount,label = label), nudge_x = 1, color = '#6da7de')+
   geom_line(data = RestofEng_ind2009, aes(x = period_start, 
                                           y = indexed_headcount, group = 1), 
             color = '#5ea15d', size = 1) +
    geom_label_repel(data = RestofEng_ind2009, aes(x = period_start, y = indexed_headcount, label = label), nudge_x = 1, color = '#5ea15d')+
  geom_hline(yintercept=100)+
   theme(plot.title = element_text(size = 16)) +
  theme(legend.position = "right") +
   scale_color_manual(name="", values=c('#d82222','#6da7de','#5ea15d'), labels=c("Inner London", "Outer London","Rest of England and Wales")) +
   scale_y_continuous(labels = label_number(suffix = "%"))+ 
   labs(title= "Change in state-funded full-time primary school pupils, 2009 - 2022",
   subtitle = "Indexed to 2009",
       caption = paste0("Source: ONS, Chart: GLA demography"))
LondonZone_orNot_ind2009_lines



ggsave (filename = (paste0(chart_dir, "Schools_Prim_LondonZone_orNot_ind2009_lines.png")),
         plot = LondonZone_orNot_ind2009_lines,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")


# ggplotly(LondonZone_orNot_ind2009_lines, tooltip = "text") %>%
#   style(hoverlabel = list(bgcolor = "white")) %>%
#   layout(title= list(x = 0.05,
#                      text = "<b>State-funded full-time primary school pupils, 2009 - 2022, indexed to 2009<b>", 
#                      font=list(size = 15, family = "Arial")))



```



```{r fig_London_Sec_schools_line_1, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

catcolour2 = rev(c('#d82222','#6da7de'))

# Aggregate by Zone of London

agg_input_london_secondary_schools <- input_all_schools_data %>%
  filter(grepl('E09', new_la_code)) %>%
  filter(la_name.x != "City of London") %>%
  filter(age > 10) %>%
  filter(type == "State-funded") %>%
  group_by(period_start, cityORcounty_name) %>% 
  summarise(agg_full_time = sum(full_time)) %>%
 # mutate(Year = as.character(year)) %>%
  data.frame()

London_sec_schools_agg_lines <- agg_input_london_secondary_schools %>%
   ggplot(aes(x = period_start, y = agg_full_time/1000, group = cityORcounty_name, color = cityORcounty_name,
             text = paste("Year  :", period_start,
                            "<br>Zone : ", cityORcounty_name,
                            "<br>Headcount : ", round(agg_full_time, digits = 0))
  )) +
  theme_gla() +
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right") +
  geom_line(size = 1) + 
  scale_color_manual(name='Zone:', values = rev(catcolour2)) +
  labs(title= "State-funded full-time secondary school pupils by Zone, London, 2009 - 2022", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
London_sec_schools_agg_lines

```


```{r fig_London_Sec_schools_line_2, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

# Index aggregated values to 2009 value

London_sec_schools_agg_ind2009_lines <- agg_input_london_secondary_schools %>%
   group_by(cityORcounty_name) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 
   ggplot(aes(x = period_start, y = indexed_headcount, group = cityORcounty_name, color = cityORcounty_name
             , text = paste("Year  :", period_start,
                            "<br>Zone : ", cityORcounty_name,
                            "<br>Head count as % of 2009 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line(size = 1) + 
  geom_hline(yintercept=100)+
   theme(plot.title = element_text(size = 16)) + # , hjust = 0.5
  theme(legend.position = "right") +
 # scale_y_continuous(breaks = seq(88, 102, 2)) + #, limits = c(88, 102)) +
 scale_color_manual(name='Zone:', values = rev(catcolour2)) +
  labs(title= "State-funded full-time secondary school pupils by Zone, London, 2009 - 2022",
  subtitle = "Indexed to 2009", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
London_sec_schools_agg_ind2009_lines



```


```{r fig_Rest_ofEng_Sec_schools_line_1, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

my_pal = gla_pal(palette_type = "categorical",
        palette_name = "core", n = 9)

# Now plot secondary schools data by English region

# Aggregate by region 

region_secondary_schools <- input_all_schools_data %>%
  filter(la_name.x != "City of London") %>%
  filter(age > 10) %>%
  filter(type == "State-funded") %>%
  group_by(period_start, region_name) %>% 
  summarise(agg_full_time = sum(full_time)) %>%
 # mutate(Year = as.character(year)) %>%
  data.frame()

regions_secondary_schools_lines <- region_secondary_schools %>%
    mutate(label = if_else(period_start == max(period_start), 
                         as.character(region_name),NA_character_)) %>%
   ggplot(aes(x = period_start, y = agg_full_time/1000, group = region_name, color = region_name,
             text = paste("Year  :", period_start,
                            "<br>Zone : ", region_name,
                            "<br>Headcount : ", round(agg_full_time, digits = 0))
  )) +
  theme_gla() +
  theme(plot.title = element_text(size = 16)) +  # ,hjust = 0.5
  theme(legend.position = "right") +
  geom_line(size = 1) + 
  scale_color_manual(name='Zone:', values = my_pal, guide = FALSE) +
    geom_label_repel(aes(label = label))+
  labs(title= "State-funded full-time primary school pupils, by region of England, 2009 - 2022", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
regions_secondary_schools_lines

```
           



```{r fig_Rest_ofEng_Sec_schools_line_2, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

# Index aggregated values to 2009 value

region_ind2009_lines <- region_secondary_schools %>%
   group_by(region_name) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 
  mutate(label = if_else(period_start == max(period_start), 
                         as.character(region_name),NA_character_)) %>%
   ggplot(aes(x = period_start, y = indexed_headcount, group = region_name, color = region_name
             , text = paste("Year  :", period_start,
                            "<br>Zone : ", region_name,
                            "<br>Head count as % of 2009 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line(size=1) + 
  geom_hline(yintercept=100)+
   theme(plot.title = element_text(size = 16)) +
  theme(legend.position = "right") +
 # scale_y_continuous(breaks = seq(88, 102, 2)) + #, limits = c(88, 102)) +
 scale_color_manual(name='Zone:', values = my_pal, guide = FALSE) +
    geom_label_repel(aes(label = label))+
  labs(title= "Change in state-funded full-time secondary school pupils",
  subtitle = "By region of England, 2009 - 2022, indexed to 2009", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
region_ind2009_lines

# ggsave (filename = (paste0(chart_dir, "region_ind2009_lines.png")),
#          plot = region_ind2009_lines,
#          device = "png",
#          dpi=600,
#          width = 9,
#          units = "in")
# 
# 
# ggplotly(region_ind2009_lines, tooltip = "text") %>%
#   style(hoverlabel = list(bgcolor = "white")) %>%
#   layout(title= list(x = 0.05,
#                      text = "<b>State-funded full-time secondary school pupils, Regions, 2009 - 2022, indexed to 2009<b>", 
#                      font=list(size = 15, family = "Arial")))


```


```{r fig_Rest_ofEng_Sec_schools_line_3, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

# Aggregate to two categories, London and the rest of England, and index to 2009 value

catcolour2 = rev(c('#e41a1c','#377eb8'))

London_orNot <- region_secondary_schools %>%
  mutate(london = case_when(region_name == "London" ~ "London",  TRUE ~ "Rest of England")) %>%
  mutate(london_factor = as.factor(london)) %>%
   group_by(period_start, london_factor) %>% 
  summarise(agg_agg_full_time = sum(agg_full_time)) %>%
  data.frame()
  
London_orNot_ind2009_lines <- London_orNot %>%
   group_by(london_factor) %>% 
   mutate(indexed_headcount = (agg_agg_full_time/first(agg_agg_full_time))*100) %>% 
    mutate(label = if_else(period_start == max(period_start), 
                         as.character(london_factor),NA_character_)) %>%
   ggplot(aes(x = period_start, y = indexed_headcount, group = london_factor, color = london_factor
             , text = paste("Year  :", period_start,
                            "<br>Zone : ", london_factor,
                            "<br>Head count as % of 2009 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line(size = 1) + 
  geom_hline(yintercept=100)+
   theme(plot.title = element_text(size = 16)) +
  theme(legend.position = "right") +
      geom_label_repel(aes(label = label))+
 scale_colour_manual(values=c("#943fa6", "#5ea15d"), 
                       name="Zone", guide = FALSE) +
labs(title= "State-funded full-time secondary school pupils, 2009 - 2022",
     subtitle = "Indexed to 2009", 
       caption = paste0("Source: ONS, Chart: GLA demography"))
London_orNot_ind2009_lines


```


```{r fig_Rest_ofEng_Sec_schools_line_4, fig.height = 5.56, fig.width = 9,   echo=FALSE, warning=FALSE, message=FALSE}

# Add rest of England indexed plot to London zone indexed plot

Inner_London_schools_agg_ind2009 <- agg_input_london_secondary_schools %>%
   group_by(cityORcounty_name) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 
   filter(cityORcounty_name == "Inner London") %>%
      mutate(label = if_else(period_start == max(period_start), 
                         as.character(cityORcounty_name),NA_character_)) %>%
  data.frame()

Outer_London_schools_agg_ind2009 <- agg_input_london_secondary_schools %>%
   group_by(cityORcounty_name) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 
   filter(cityORcounty_name == "Outer London") %>%
      mutate(label = if_else(period_start == max(period_start), 
                         as.character(cityORcounty_name),NA_character_)) %>%
  data.frame()

RestofEng_ind2009 <- London_orNot %>%
   group_by(london_factor) %>% 
   mutate(indexed_headcount = (agg_agg_full_time/first(agg_agg_full_time))*100) %>% 
  filter(london_factor == "Rest of England") %>%
      mutate(label = if_else(period_start == max(period_start), 
                         as.character(london_factor),NA_character_)) %>%
  data.frame()

LondonZone_orNot_ind2009_lines <-
   ggplot() +
  theme_gla() +
   geom_line(data = Inner_London_schools_agg_ind2009, aes(x = period_start, y = indexed_headcount, group = 1), color = '#d82222', size = 1) +
     geom_label_repel(data = Inner_London_schools_agg_ind2009,aes(x = period_start, y = indexed_headcount,label = label), nudge_x = 1, color = '#d82222')+
    geom_line(data = Outer_London_schools_agg_ind2009, aes(x = period_start, y = indexed_headcount, group = 1), color = '#6da7de', size = 1 ) +
   geom_label_repel(data = Outer_London_schools_agg_ind2009,aes(x = period_start, y = indexed_headcount,label = label), nudge_x = 1,  color = '#6da7de')+
   geom_line(data = RestofEng_ind2009, aes(x = period_start, y = indexed_headcount, group = 1), color = "#5ea15d", size = 1) +
    geom_label_repel(data = RestofEng_ind2009,aes(x = period_start, y = indexed_headcount,label = label), nudge_x = 1, color = "#5ea15d")+
  geom_hline(yintercept=100)+
   theme(plot.title = element_text(size = 16)) +  #hjust = 0.5
  theme(legend.position = "right") +
  #     scale_color_manual(name="zone", values=c( '#d82222','#6da7de',"#5ea15d"), guide = FALSE)+
   labs(title= "Change in state-funded full-time secondary school pupils, 2009 - 2022",
        subtitle = "Indexed to 2009",
       caption = paste0("Source: ONS, Chart: GLA demography"))
LondonZone_orNot_ind2009_lines


ggsave (filename = (paste0(chart_dir, "Schools_Sec_LondonZone_orNot_ind2009_lines.png")),
         plot = LondonZone_orNot_ind2009_lines,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")
# 



```

